-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('classicddz_pb')


local E_CARD_TYPE = protobuf.EnumDescriptor();
local E_CARD_TYPE_E_CARD_0_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_1_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_2_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_3_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_3_1_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_3_2_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_4_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_4_1_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_4_2_1_ENUM = protobuf.EnumValueDescriptor();
local E_CARD_TYPE_E_CARD_4_2_2_ENUM = protobuf.EnumValueDescriptor();
local CLASSICDDZ_CARDS = protobuf.Descriptor();
local CLASSICDDZ_CARDS_E_TYPE_FIELD = protobuf.FieldDescriptor();
local CLASSICDDZ_CARDS_CARDS_FIELD = protobuf.FieldDescriptor();
local CLASSICDDZ_CARDS_DESC_FIELD = protobuf.FieldDescriptor();

E_CARD_TYPE_E_CARD_0_ENUM.name = "e_card_0"
E_CARD_TYPE_E_CARD_0_ENUM.index = 0
E_CARD_TYPE_E_CARD_0_ENUM.number = 0
E_CARD_TYPE_E_CARD_1_ENUM.name = "e_card_1"
E_CARD_TYPE_E_CARD_1_ENUM.index = 1
E_CARD_TYPE_E_CARD_1_ENUM.number = 65797
E_CARD_TYPE_E_CARD_2_ENUM.name = "e_card_2"
E_CARD_TYPE_E_CARD_2_ENUM.index = 2
E_CARD_TYPE_E_CARD_2_ENUM.number = 131331
E_CARD_TYPE_E_CARD_3_ENUM.name = "e_card_3"
E_CARD_TYPE_E_CARD_3_ENUM.index = 3
E_CARD_TYPE_E_CARD_3_ENUM.number = 196866
E_CARD_TYPE_E_CARD_3_1_ENUM.name = "e_card_3_1"
E_CARD_TYPE_E_CARD_3_1_ENUM.index = 4
E_CARD_TYPE_E_CARD_3_1_ENUM.number = 200978
E_CARD_TYPE_E_CARD_3_2_ENUM.name = "e_card_3_2"
E_CARD_TYPE_E_CARD_3_2_ENUM.index = 5
E_CARD_TYPE_E_CARD_3_2_ENUM.number = 205074
E_CARD_TYPE_E_CARD_4_ENUM.name = "e_card_4"
E_CARD_TYPE_E_CARD_4_ENUM.index = 6
E_CARD_TYPE_E_CARD_4_ENUM.number = 262400
E_CARD_TYPE_E_CARD_4_1_ENUM.name = "e_card_4_1"
E_CARD_TYPE_E_CARD_4_1_ENUM.index = 7
E_CARD_TYPE_E_CARD_4_1_ENUM.number = 266512
E_CARD_TYPE_E_CARD_4_2_1_ENUM.name = "e_card_4_2_1"
E_CARD_TYPE_E_CARD_4_2_1_ENUM.index = 8
E_CARD_TYPE_E_CARD_4_2_1_ENUM.number = 266528
E_CARD_TYPE_E_CARD_4_2_2_ENUM.name = "e_card_4_2_2"
E_CARD_TYPE_E_CARD_4_2_2_ENUM.index = 9
E_CARD_TYPE_E_CARD_4_2_2_ENUM.number = 270624
E_CARD_TYPE.name = "e_card_type"
E_CARD_TYPE.full_name = ".e_card_type"
E_CARD_TYPE.values = {E_CARD_TYPE_E_CARD_0_ENUM,E_CARD_TYPE_E_CARD_1_ENUM,E_CARD_TYPE_E_CARD_2_ENUM,E_CARD_TYPE_E_CARD_3_ENUM,E_CARD_TYPE_E_CARD_3_1_ENUM,E_CARD_TYPE_E_CARD_3_2_ENUM,E_CARD_TYPE_E_CARD_4_ENUM,E_CARD_TYPE_E_CARD_4_1_ENUM,E_CARD_TYPE_E_CARD_4_2_1_ENUM,E_CARD_TYPE_E_CARD_4_2_2_ENUM}
CLASSICDDZ_CARDS_E_TYPE_FIELD.name = "e_type"
CLASSICDDZ_CARDS_E_TYPE_FIELD.full_name = ".classicddz_cards.e_type"
CLASSICDDZ_CARDS_E_TYPE_FIELD.number = 1
CLASSICDDZ_CARDS_E_TYPE_FIELD.index = 0
CLASSICDDZ_CARDS_E_TYPE_FIELD.label = 2
CLASSICDDZ_CARDS_E_TYPE_FIELD.has_default_value = false
CLASSICDDZ_CARDS_E_TYPE_FIELD.default_value = nil
CLASSICDDZ_CARDS_E_TYPE_FIELD.enum_type = E_CARD_TYPE
CLASSICDDZ_CARDS_E_TYPE_FIELD.type = 14
CLASSICDDZ_CARDS_E_TYPE_FIELD.cpp_type = 8

CLASSICDDZ_CARDS_CARDS_FIELD.name = "cards"
CLASSICDDZ_CARDS_CARDS_FIELD.full_name = ".classicddz_cards.cards"
CLASSICDDZ_CARDS_CARDS_FIELD.number = 2
CLASSICDDZ_CARDS_CARDS_FIELD.index = 1
CLASSICDDZ_CARDS_CARDS_FIELD.label = 2
CLASSICDDZ_CARDS_CARDS_FIELD.has_default_value = false
CLASSICDDZ_CARDS_CARDS_FIELD.default_value = ""
CLASSICDDZ_CARDS_CARDS_FIELD.type = 12
CLASSICDDZ_CARDS_CARDS_FIELD.cpp_type = 9

CLASSICDDZ_CARDS_DESC_FIELD.name = "desc"
CLASSICDDZ_CARDS_DESC_FIELD.full_name = ".classicddz_cards.desc"
CLASSICDDZ_CARDS_DESC_FIELD.number = 3
CLASSICDDZ_CARDS_DESC_FIELD.index = 2
CLASSICDDZ_CARDS_DESC_FIELD.label = 2
CLASSICDDZ_CARDS_DESC_FIELD.has_default_value = false
CLASSICDDZ_CARDS_DESC_FIELD.default_value = ""
CLASSICDDZ_CARDS_DESC_FIELD.type = 12
CLASSICDDZ_CARDS_DESC_FIELD.cpp_type = 9

CLASSICDDZ_CARDS.name = "classicddz_cards"
CLASSICDDZ_CARDS.full_name = ".classicddz_cards"
CLASSICDDZ_CARDS.nested_types = {}
CLASSICDDZ_CARDS.enum_types = {}
CLASSICDDZ_CARDS.fields = {CLASSICDDZ_CARDS_E_TYPE_FIELD, CLASSICDDZ_CARDS_CARDS_FIELD, CLASSICDDZ_CARDS_DESC_FIELD}
CLASSICDDZ_CARDS.is_extendable = false
CLASSICDDZ_CARDS.extensions = {}

classicddz_cards = protobuf.Message(CLASSICDDZ_CARDS)
e_card_0 = 0
e_card_1 = 65797
e_card_2 = 131331
e_card_3 = 196866
e_card_3_1 = 200978
e_card_3_2 = 205074
e_card_4 = 262400
e_card_4_1 = 266512
e_card_4_2_1 = 266528
e_card_4_2_2 = 270624

