// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_login_2eproto();
void protobuf_AssignDesc_login_2eproto();
void protobuf_ShutdownFile_login_2eproto();

class msg_request_enter_game;
class msg_response_enter_game;

enum e_login_msgid {
  request_enter_game = 10001,
  response_enter_game = 10002
};
bool e_login_msgid_IsValid(int value);
const e_login_msgid e_login_msgid_MIN = request_enter_game;
const e_login_msgid e_login_msgid_MAX = response_enter_game;
const int e_login_msgid_ARRAYSIZE = e_login_msgid_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_login_msgid_descriptor();
inline const ::std::string& e_login_msgid_Name(e_login_msgid value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_login_msgid_descriptor(), value);
}
inline bool e_login_msgid_Parse(
    const ::std::string& name, e_login_msgid* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_login_msgid>(
    e_login_msgid_descriptor(), name, value);
}
// ===================================================================

class msg_request_enter_game : public ::google::protobuf::Message {
 public:
  msg_request_enter_game();
  virtual ~msg_request_enter_game();

  msg_request_enter_game(const msg_request_enter_game& from);

  inline msg_request_enter_game& operator=(const msg_request_enter_game& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_request_enter_game& default_instance();

  void Swap(msg_request_enter_game* other);

  // implements Message ----------------------------------------------

  msg_request_enter_game* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const msg_request_enter_game& from);
  void MergeFrom(const msg_request_enter_game& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::int64 uid() const;
  inline void set_uid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:msg_request_enter_game)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 uid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static msg_request_enter_game* default_instance_;
};
// -------------------------------------------------------------------

class msg_response_enter_game : public ::google::protobuf::Message {
 public:
  msg_response_enter_game();
  virtual ~msg_response_enter_game();

  msg_response_enter_game(const msg_response_enter_game& from);

  inline msg_response_enter_game& operator=(const msg_response_enter_game& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const msg_response_enter_game& default_instance();

  void Swap(msg_response_enter_game* other);

  // implements Message ----------------------------------------------

  msg_response_enter_game* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const msg_response_enter_game& from);
  void MergeFrom(const msg_response_enter_game& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 err = 1;
  inline bool has_err() const;
  inline void clear_err();
  static const int kErrFieldNumber = 1;
  inline ::google::protobuf::int32 err() const;
  inline void set_err(::google::protobuf::int32 value);

  // required int64 uid = 2;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 2;
  inline ::google::protobuf::int64 uid() const;
  inline void set_uid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:msg_response_enter_game)
 private:
  inline void set_has_err();
  inline void clear_has_err();
  inline void set_has_uid();
  inline void clear_has_uid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 uid_;
  ::google::protobuf::int32 err_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_login_2eproto();
  friend void protobuf_AssignDesc_login_2eproto();
  friend void protobuf_ShutdownFile_login_2eproto();

  void InitAsDefaultInstance();
  static msg_response_enter_game* default_instance_;
};
// ===================================================================


// ===================================================================

// msg_request_enter_game

// required int64 uid = 1;
inline bool msg_request_enter_game::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void msg_request_enter_game::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void msg_request_enter_game::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void msg_request_enter_game::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::int64 msg_request_enter_game::uid() const {
  return uid_;
}
inline void msg_request_enter_game::set_uid(::google::protobuf::int64 value) {
  set_has_uid();
  uid_ = value;
}

// -------------------------------------------------------------------

// msg_response_enter_game

// required int32 err = 1;
inline bool msg_response_enter_game::has_err() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void msg_response_enter_game::set_has_err() {
  _has_bits_[0] |= 0x00000001u;
}
inline void msg_response_enter_game::clear_has_err() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void msg_response_enter_game::clear_err() {
  err_ = 0;
  clear_has_err();
}
inline ::google::protobuf::int32 msg_response_enter_game::err() const {
  return err_;
}
inline void msg_response_enter_game::set_err(::google::protobuf::int32 value) {
  set_has_err();
  err_ = value;
}

// required int64 uid = 2;
inline bool msg_response_enter_game::has_uid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void msg_response_enter_game::set_has_uid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void msg_response_enter_game::clear_has_uid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void msg_response_enter_game::clear_uid() {
  uid_ = GOOGLE_LONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::int64 msg_response_enter_game::uid() const {
  return uid_;
}
inline void msg_response_enter_game::set_uid(::google::protobuf::int64 value) {
  set_has_uid();
  uid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_login_msgid>() {
  return ::e_login_msgid_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
