// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: poker.proto

#ifndef PROTOBUF_poker_2eproto__INCLUDED
#define PROTOBUF_poker_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_poker_2eproto();
void protobuf_AssignDesc_poker_2eproto();
void protobuf_ShutdownFile_poker_2eproto();

class card_info;

enum e_table_type {
  e_classic_doudizhu = 1
};
bool e_table_type_IsValid(int value);
const e_table_type e_table_type_MIN = e_classic_doudizhu;
const e_table_type e_table_type_MAX = e_classic_doudizhu;
const int e_table_type_ARRAYSIZE = e_table_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_table_type_descriptor();
inline const ::std::string& e_table_type_Name(e_table_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_table_type_descriptor(), value);
}
inline bool e_table_type_Parse(
    const ::std::string& name, e_table_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_table_type>(
    e_table_type_descriptor(), name, value);
}
// ===================================================================

class card_info : public ::google::protobuf::Message {
 public:
  card_info();
  virtual ~card_info();

  card_info(const card_info& from);

  inline card_info& operator=(const card_info& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const card_info& default_instance();

  void Swap(card_info* other);

  // implements Message ----------------------------------------------

  card_info* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const card_info& from);
  void MergeFrom(const card_info& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 card_type = 1;
  inline bool has_card_type() const;
  inline void clear_card_type();
  static const int kCardTypeFieldNumber = 1;
  inline ::google::protobuf::int32 card_type() const;
  inline void set_card_type(::google::protobuf::int32 value);

  // required bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:card_info)
 private:
  inline void set_has_card_type();
  inline void clear_has_card_type();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* data_;
  ::google::protobuf::int32 card_type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_poker_2eproto();
  friend void protobuf_AssignDesc_poker_2eproto();
  friend void protobuf_ShutdownFile_poker_2eproto();

  void InitAsDefaultInstance();
  static card_info* default_instance_;
};
// ===================================================================


// ===================================================================

// card_info

// required int32 card_type = 1;
inline bool card_info::has_card_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void card_info::set_has_card_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void card_info::clear_has_card_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void card_info::clear_card_type() {
  card_type_ = 0;
  clear_has_card_type();
}
inline ::google::protobuf::int32 card_info::card_type() const {
  return card_type_;
}
inline void card_info::set_card_type(::google::protobuf::int32 value) {
  set_has_card_type();
  card_type_ = value;
}

// required bytes data = 2;
inline bool card_info::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void card_info::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void card_info::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void card_info::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& card_info::data() const {
  return *data_;
}
inline void card_info::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void card_info::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void card_info::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* card_info::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* card_info::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void card_info::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_table_type>() {
  return ::e_table_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_poker_2eproto__INCLUDED
